#!/usr/bin/env python3
"""
GAKURI MIDI Player — Play MIDI files generated by GAKURI
Uses pygame.midi or fluidsynth for playback

Usage:
  python play_midi.py <midi-file>          # Play single file
  python play_midi.py --batch              # Play all generated MIDI files
  python play_midi.py --demo               # Generate + play sample progression
  python play_midi.py --list-instruments   # List available MIDI instruments
"""

import argparse
import os
import sys
import glob
import time

# Try pygame first (comes with Python, no extra install needed)
try:
    import pygame
    import pygame.midi
    HAS_PYGAME = True
except ImportError:
    HAS_PYGAME = False

# Try fluidsynth for better sound quality
try:
    import fluidsynth
    HAS_FLUIDSYNTH = True
except ImportError:
    HAS_FLUIDSYNTH = False

# Try pretty_midi for analysis
try:
    import pretty_midi
    HAS_PRETTY_MIDI = True
except ImportError:
    HAS_PRETTY_MIDI = False


# ── MIDI Instrument Map ──────────────────────────────────────────────
INSTRUMENTS = {
    0: "Acoustic Grand Piano",
    1: "Bright Acoustic Piano",
    2: "Electric Grand Piano",
    3: "Honky-tonk Piano",
    4: "Electric Piano 1 (Rhodes)",
    5: "Electric Piano 2 (Chorused)",
    6: "Harpsichord",
    7: "Clavinet",
    8: "Celesta",
    9: "Glockenspiel",
    10: "Music Box",
    11: "Vibraphone",
    12: "Marimba",
    13: "Xylophone",
    14: "Tubular Bells",
    15: "Dulcimer",
    16: "Drawbar Organ",
    17: "Percussive Organ",
    18: "Rock Organ",
    19: "Church Organ",
    20: "Reed Organ",
    21: "Accordion",
    22: "Harmonica",
    23: "Tango Accordion",
    24: "Acoustic Guitar (nylon)",
    25: "Acoustic Guitar (steel)",
    26: "Electric Guitar (jazz)",
    27: "Electric Guitar (clean)",
    28: "Electric Guitar (muted)",
    29: "Overdriven Guitar",
    30: "Distortion Guitar",
    31: "Guitar Harmonics",
    32: "Acoustic Bass",
    33: "Electric Bass (finger)",
    34: "Electric Bass (pick)",
    35: "Fretless Bass",
    36: "Slap Bass 1",
    37: "Slap Bass 2",
    38: "Synth Bass 1",
    39: "Synth Bass 2",
    40: "Violin",
    41: "Viola",
    42: "Cello",
    43: "Contrabass",
    44: "Tremolo Strings",
    45: "Pizzicato Strings",
    46: "Orchestral Harp",
    47: "Timpani",
    48: "String Ensemble 1",
    49: "String Ensemble 2",
    50: "Synth Strings 1",
    51: "Synth Strings 2",
    52: "Choir Aahs",
    53: "Voice Oohs",
    54: "Synth Voice",
    55: "Orchestra Hit",
    56: "Trumpet",
    57: "Trombone",
    58: "Tuba",
    59: "Muted Trumpet",
    60: "French Horn",
    61: "Brass Section",
    62: "Synth Brass 1",
    63: "Synth Brass 2",
    64: "Soprano Sax",
    65: "Alto Sax",
    66: "Tenor Sax",
    67: "Baritone Sax",
    68: "Oboe",
    69: "English Horn",
    70: "Bassoon",
    71: "Clarinet",
    72: "Piccolo",
    73: "Flute",
    74: "Recorder",
    75: "Pan Flute",
    76: "Blown Bottle",
    77: "Shakuhachi",
    78: "Whistle",
    79: "Ocarina",
    80: "Lead 1 (square)",
    81: "Lead 2 (sawtooth)",
    82: "Lead 3 (calliope)",
    83: "Lead 4 (chiff)",
    84: "Lead 5 (charang)",
    85: "Lead 6 (voice)",
    86: "Lead 7 (fifths)",
    87: "Lead 8 (bass + lead)",
    88: "Pad 1 (new age)",
    89: "Pad 2 (warm)",
    90: "Pad 3 (polysynth)",
    91: "Pad 4 (choir)",
    92: "Pad 5 (bowed)",
    93: "Pad 6 (metallic)",
    94: "Pad 7 (halo)",
    95: "Pad 8 (sweep)",
    96: "FX 1 (rain)",
    97: "FX 2 (soundtrack)",
    98: "FX 3 (crystal)",
    99: "FX 4 (atmosphere)",
    100: "FX 5 (brightness)",
    101: "FX 6 (goblins)",
    102: "FX 7 (echoes)",
    103: "FX 8 (sci-fi)",
}

# Jazz-friendly instrument presets
JAZZ_PRESETS = {
    "piano": 0,         # Acoustic Grand Piano
    "rhodes": 4,        # Electric Piano 1
    "vibes": 11,        # Vibraphone
    "organ": 16,        # Drawbar Organ
    "guitar": 26,       # Electric Guitar (jazz)
    "strings": 48,      # String Ensemble 1
    "sax": 66,          # Tenor Sax
    "bass": 33,         # Electric Bass (finger)
}


# ── Playback Methods ─────────────────────────────────────────────────

def play_with_pygame(midi_file):
    """Play MIDI file using pygame.mixer.music"""
    if not HAS_PYGAME:
        print("pygame not installed. Run: pip install pygame")
        return False
    
    print(f"🎵 Playing: {midi_file}")
    print(f"   Press Ctrl+C to stop\n")
    
    pygame.mixer.init()
    pygame.mixer.music.load(midi_file)
    pygame.mixer.music.play()
    
    while pygame.mixer.music.get_busy():
        time.sleep(0.5)
    
    pygame.mixer.quit()
    return True


def play_with_fluidsynth(midi_file, soundfont=None):
    """Play MIDI file using FluidSynth (better quality)"""
    if not HAS_FLUIDSYNTH:
        print("fluidsynth not installed. Run: pip install pyfluidsynth")
        return False
    
    # Find a soundfont
    if soundfont is None:
        # Try common soundfont locations
        sf_candidates = [
            "/usr/share/sounds/sf2/FluidR3_GM.sf2",
            "/usr/share/soundfonts/FluidR3_GM.sf2",
            os.path.expanduser("~/.local/share/sounds/sf2/FluidR3_GM.sf2"),
            os.path.join(os.path.dirname(__file__), "soundfonts", "FluidR3_GM.sf2"),
        ]
        for sf in sf_candidates:
            if os.path.exists(sf):
                soundfont = sf
                break
        else:
            print("⚠ No soundfont found. Install one or specify with --soundfont <path>")
            print("  Recommended: FluidR3_GM.sf2 or GeneralUser_GS.sf2")
            return False
    
    print(f"🎹 Playing: {midi_file}")
    print(f"   Soundfont: {soundfont}")
    print(f"   Press Ctrl+C to stop\n")
    
    fs = fluidsynth.Synth()
    fs.start()
    sfid = fs.sfload(soundfont)
    
    # Parse MIDI file and play
    fs.player_play_midi(midi_file)
    
    try:
        while fs.player_get_status() == fluidsynth.FLUID_PLAYER_PLAYING:
            time.sleep(0.5)
    except KeyboardInterrupt:
        pass
    
    fs.stop()
    fs.delete()
    return True


def analyze_midi(midi_file):
    """Analyze and display MIDI file contents using pretty_midi"""
    if not HAS_PRETTY_MIDI:
        print("pretty_midi not installed. Run: pip install pretty_midi")
        return
    
    print(f"\n📊 Analysis: {midi_file}")
    print("=" * 50)
    
    pm = pretty_midi.PrettyMIDI(midi_file)
    
    print(f"  Tempo: {pm.get_tempo_changes()[0][0]:.1f} BPM")
    print(f"  Time signature: {pm.time_signature_changes}")
    print(f"  Duration: {pm.get_end_time():.1f} seconds")
    print(f"  Instruments: {len(pm.instruments)}")
    
    for i, inst in enumerate(pm.instruments):
        print(f"    {i+1}. {inst.name or INSTRUMENTS.get(inst.program, f'Program {inst.program}')} "
              f"(program={inst.program}, notes={len(inst.notes)})")
    
    # Show chord events
    print(f"\n  Chord sequence:")
    all_notes = sorted(pm.get_onsets())
    chord_notes = {}
    for onset in all_notes:
        for inst in pm.instruments:
            for note in inst.notes:
                if abs(note.start - onset) < 0.05:
                    if onset not in chord_notes:
                        chord_notes[onset] = []
                    chord_notes[onset].append(note.pitch)
    
    for onset in sorted(chord_notes.keys()):
        pitches = sorted(set(chord_notes[onset]))
        note_names = [f"{p % 12:2d}" for p in pitches]
        print(f"    {onset:6.2f}s: {pitches}")


# ── Demo: Generate & Play ────────────────────────────────────────────

def generate_and_play():
    """Generate a sample progression and play it"""
    print("╔══════════════════════════════════════════════════╗")
    print("║  GAKURI — Generate & Play Demo                  ║")
    print("╚══════════════════════════════════════════════════╝\n")
    
    midi_dir = os.path.join(os.path.dirname(__file__), "midi-output")
    os.makedirs(midi_dir, exist_ok=True)
    
    # List generated MIDI files
    midi_files = glob.glob(os.path.join(midi_dir, "*.mid"))
    
    if not midi_files:
        print("⚠ No MIDI files found!")
        print("\nTo generate MIDI files from GAKURI (Common Lisp):")
        print("  1. Load GAKURI in SBCL/CLISP")
        print("  2. Run: (export-progression-midi progression key :mood :yearning)")
        print("  3. Then run this script again\n")
        print("  OR: Generate manually with the HTML player below.")
        return
    
    print(f"Found {len(midi_files)} MIDI files:\n")
    for i, f in enumerate(midi_files):
        name = os.path.basename(f)
        size = os.path.getsize(f)
        print(f"  {i+1}. {name} ({size} bytes)")
    
    print(f"\n{'='*50}")
    
    # Play all files
    for midi_file in sorted(midi_files):
        name = os.path.basename(midi_file)
        mood = name.replace("gakuri-", "").replace(".mid", "").upper()
        print(f"\n{'='*50}")
        print(f"  🎵 {mood}")
        print(f"{'='*50}")
        
        # Try FluidSynth first (better quality), fallback to pygame
        if HAS_FLUIDSYNTH:
            if not play_with_fluidsynth(midi_file):
                play_with_pygame(midi_file)
        else:
            play_with_pygame(midi_file)


# ── CLI ──────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="GAKURI MIDI Player")
    parser.add_argument("midi_file", nargs="?", help="MIDI file to play")
    parser.add_argument("--batch", action="store_true", help="Play all MIDI files in output directory")
    parser.add_argument("--demo", action="store_true", help="Generate + play demo")
    parser.add_argument("--analyze", action="store_true", help="Analyze MIDI file instead of playing")
    parser.add_argument("--list-instruments", action="store_true", help="List MIDI instruments")
    parser.add_argument("--soundfont", help="Path to SoundFont (.sf2)")
    parser.add_argument("--instrument", type=int, help="MIDI program number (0-127)")
    
    args = parser.parse_args()
    
    if args.list_instruments:
        print("MIDI Instruments (GM):")
        for num, name in sorted(INSTRUMENTS.items()):
            print(f"  {num:3d}. {name}")
        print(f"\nJazz-friendly presets:")
        for name, num in JAZZ_PRESETS.items():
            print(f"  {name}: {num} ({INSTRUMENTS[num]})")
        return
    
    if args.demo:
        generate_and_play()
        return
    
    if args.batch:
        midi_dir = os.path.join(os.path.dirname(__file__), "midi-output")
        midi_files = glob.glob(os.path.join(midi_dir, "*.mid"))
        if not midi_files:
            print("No MIDI files found in midi-output/")
            return
        for f in sorted(midi_files):
            if args.analyze:
                analyze_midi(f)
            else:
                if HAS_FLUIDSYNTH:
                    play_with_fluidsynth(f, args.soundfont)
                else:
                    play_with_pygame(f)
        return
    
    if args.midi_file:
        if not os.path.exists(args.midi_file):
            print(f"File not found: {args.midi_file}")
            sys.exit(1)
        
        if args.analyze:
            analyze_midi(args.midi_file)
        else:
            if HAS_FLUIDSYNTH:
                play_with_fluidsynth(args.midi_file, args.soundfont)
            else:
                play_with_pygame(args.midi_file)
        return
    
    # No arguments: show help
    parser.print_help()
    print(f"""
Quick start:
  python play_midi.py --demo                    # Demo mode
  python play_midi.py midi-output/gakuri-yearning.mid  # Play specific
  python play_midi.py --batch                   # Play all
  python play_midi.py --analyze file.mid        # Analyze
  python play_midi.py --list-instruments        # List instruments
""")


if __name__ == "__main__":
    main()
